name: ci
on:
  push:
jobs:
  test:
    name: Node.js v${{ matrix.node-version }}
    strategy:
      matrix:
        node-version:
          - 22
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: Install
        run: npm ci
      - name: Test
        run: npm test
