name: github-pages
on:
  push:
    branches: main
jobs:
  main:
    permissions:
      pages: write
      id-token: write
    environment: github-pages
    runs-on: ubuntu-latest
    container: alpine@sha256:28bd5fe8b56d1bd048e5babf5b10710ebe0bae67db86916198a6eec434943f8b
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - name: Build
        run: |
          apk add mdbook tar
          mdbook build
      - uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5
        with:
          path: book
      - uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5
