name: github-pages
on:
  push:
    branches: main
jobs:
  main:
    permissions:
      pages: write
      id-token: write
    environment: github-pages
    runs-on: ubuntu-latest
    container: alpine@sha256:294b683cb724975bec92580e1e685676bd4b50bda910ddb8c51d4cabeaec77e6
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Build
        run: |
          apk add mdbook tar
          mdbook build
      - uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5
        with:
          path: book
      - uses: actions/deploy-pages@368f82528645a54fb793d4d04e342629a3f51346 # v5
